### ISSUE TITLE
Error while trying to Register

### ISSUE THREAD

**Issue by bgadiel** [Shazwazza/UmbracoIdentity#18] opened 2015-09-16 14:36 UTC
Hi,
Using a fresh copy of U7.3RC, I've added UmbracoIdentity via nuget.

Issue #1: UmbracoStartup was not called just by following the Config updates. I had to replace existing owin key with: add key="owin:AutomaticAppStartup" value="true"

Issue #2: After trying to sign in with Facebook, I get the following error:
"Cannot execute without a valid/current UmbracoContext with an HttpContext assigned.
Exception Details: System.NotSupportedException: Cannot execute without a valid/current UmbracoContext with an HttpContext assigned.
Line 111:                var result = await UserManager.CreateAsync(user);
Source File: c:\Dev\Projects\TemplateUmbraco\TemplateUmbraco\Controllers\UmbracoIdentityAccountController.cs    Line: 111 
Stack Trace: 
[NotSupportedException: Cannot execute without a valid/current UmbracoContext with an HttpContext assigned.]
   Umbraco.Web.BatchedDatabaseServerMessenger.GetBatch(Boolean ensureHttpContext) +326
   Umbraco.Web.BatchedDatabaseServerMessenger.BatchMessage(IEnumerable`1 servers, ICacheRefresher refresher, MessageType messageType, IEnumerable`1 ids, Type idType, String json) +26
   Umbraco.Web.BatchedDatabaseServerMessenger.DeliverRemote(IEnumerable`1 servers, ICacheRefresher refresher, MessageType messageType, IEnumerable`1 ids, String json) +131
   Umbraco.Web.Cache.DistributedCache.Refresh(Guid factoryGuid, Func`2 getNumericId, T[] instances) +373
   Umbraco.Web.Cache.DistributedCacheExtensions.RefreshMemberCache(DistributedCache dc, IMember[] members) +191
   Umbraco.Core.Services.MemberService.Save(IMember entity, Boolean raiseEvents) +558
   UmbracoIdentity.<>c__DisplayClass1.<CreateAsync>b__0() in x:\Projects\UmbracoIdentity\src\UmbracoIdentity\UmbracoMembersUserStore.cs:70
   System.Threading.Tasks.Task.Execute() +110
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   Microsoft.AspNet.Identity.CultureAwaiter.GetResult() +60
   Microsoft.AspNet.Identity.<CreateAsync>d__0.MoveNext() +1658
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +49
   TemplateUmbraco.Controllers.<ExternalLoginConfirmation>d__e.MoveNext() in c:\Dev\Projects\TemplateUmbraco\TemplateUmbraco\Controllers\UmbracoIdentityAccountController.cs:111
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult) +143
   System.Web.Mvc.Async.<>c__DisplayClass37.<BeginInvokeAsynchronousActionMethod>b__36(IAsyncResult asyncResult) +23
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +112
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +452
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +452
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +452
   System.Web.Mvc.Async.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) +15
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +37
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +241
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +29
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +111
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +53
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +19
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +51
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +111
   System.Web.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar) +282"

Issue #3: After the error message, I am not able to login to Umbraco Back office with my admin user. Since I had only created 1 user during the installation process, I'm stuck, and not able to tell if a new user was actually added to DB (SQL CE).

Thanks.

**Comment by Shazwazza** [comment] 2015-09-16 19:12
This is a duplicate, see: https://github.com/Shazwazza/UmbracoIdentity/issues/14 

If you can retest with the latest 7.3. nightlies it should be fixed: 

* http://nightly.umbraco.org/umbraco%207.3.0/
* MyGet nightly feed: https://www.myget.org/F/umbraconightly/api/v2

Also, yes the documentation hasn't been updated for UmbracoIdentity + 7.3, since Umbraco now ships with ASP.Net Identity + Owin and requires being booted up itself. I will get new docs made soon.

**Comment by robertjf** [comment] 2015-09-22 08:16
@Shazwazza I'm seeing this same error when trying to authenticate AzureAD for members - I'm using a local Umbraco build the current repository (refreshed yesterday)

Going to dig a little deeper

**Comment by Shazwazza** [comment] 2015-09-22 09:24
Ok, if i find time i can try to replicate but not sure when I'll get to it :( If you have any time to debug what might be going on, that would be terrific. You can see how I fixed the previous issue relating to this in this repo with the async handling changes. For the most part it's because I was incorrectly returning tasks from within other tasks which doesn't carry along the syncronization context (http context) which is what the UmbracoContext is tied to. Perhaps there's other parts of the code where this isn't being taken care of correctly either.

**Comment by robertjf** [comment] 2015-09-22 09:47
That's fine, I'm currently using the Nuget package which is presenting as v. 2.0.0 - I'll upgrade to the latest repository code and see if that resolves it first.  If not, I'll just go debugging.

**Comment by robertjf** [comment] 2015-09-22 11:39
I can confirm that the current repository version has resolved this problem; just need a new Package now ;)

**Comment by Shazwazza** [comment] 2015-09-22 12:11
Fantastic and thanks for testing. I can probably get one out tonight when I get home.

**Closed** 2015-09-22 15:40 UTC
Labels: duplicate
