### ISSUE TITLE
Auth cookie authentication

### ISSUE THREAD

**Issue by adamversed** [Shazwazza/UmbracoIdentity#28] opened 2015-12-04 15:43 UTC
hi Shazwazz,

We have implemented UmbracoIdentity (very useful thanks!).  We have a very basic setup but we have something incorrect and was hoping you might spot what it is.   The scenario is:

- umbraco back office to use default implementation and user store
- front end to use our custom authentication call
- both cookie based
- authentication should not be shared between either (i.e. if you login for one you should still require login for the other)

Using a custom start up class inheriting the UmbracoDefaultOwinStartup, we call base.Configuration and then also add the configuration for our own.  All seemed fine, both areas require authentication as they should, but if we log into the front end first, then hit the backend and log in there, we get the following error:

2015-12-04 14:35:49,482 [P20344/D2/T10] ERROR Umbraco.Core.Security.AuthenticationExtensions - The current identity cannot be converted to Umbraco.Core.Security.UmbracoBackOfficeIdentity
System.InvalidOperationException: Cannot create a Umbraco.Core.Security.UmbracoBackOfficeIdentity from System.Security.Claims.ClaimsIdentity since the required claim http://umbraco.org/2015/02/identity/claims/backoffice/startcontentnode is missing

We can get around this for now for now signing out the front end user before hitting backend authentication, but I thought the scenario we want is possible and the workaround shouldn't be necessary?

We are using umbraco 7.3.2, UmbracoIdentity 2.0.1.0

Sorry if im missing any required details but I can happily supply anything needed, appreciate any insights.

Adam

**Comment by Shazwazza** [comment] 2015-12-14 10:16
Hi thanks for reporting, i'll have to have a look and replicate to see what the issue is, hopefully I'll find some time in the next week or two.

**Comment by Shazwazza** [comment] 2015-12-14 17:47
I'm pretty sure this is just because this package hasn't been updated correctly to work as expected with 7.3.x. I'll make this a duplicate of #29. I'll be releasing a new version very soon!

**Closed** 2015-12-14 17:47 UTC
Labels: duplicate
